------------------------------------------------------------------------------------------------------------------------

[2017-02-18 18:47:44 #1 explorer] 
[ObjectDB 2.6.9_09] javax.persistence.PersistenceException
Attempt to open a database file 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' that is currently in use by another process (error 141)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Attempt to open a database file 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' that is currently in use by another process
	at com.objectdb.o.MSG.d(MSG.java:62)
	at com.objectdb.o.LFL.G(LFL.java:939)
	at com.objectdb.o.LFL.B(LFL.java:885)
	at com.objectdb.o.LFL.B(LFL.java:794)
	at com.objectdb.o.SFL.<init>(SFL.java:235)
	at com.objectdb.o.MST.<init>(MST.java:123)
	at com.objectdb.o.MST.aN(MST.java:105)
	at com.objectdb.o.MSF.Vn(MSF.java:188)
	at com.objectdb.o.OMF.an(OMF.java:782)
	at com.objectdb.jpa.EMF.an(EMF.java:131)
	at com.objectdb.o.OMF.am(OMF.java:693)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:150)
	... 17 more

------------------------------------------------------------------------------------------------------------------------

[2017-02-18 19:13:10 #1 store] 
Database 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' is opened by 11148@LAPTOP-HB33B0MF

[2017-02-18 19:20:54 #2 store] 
Database 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' is closed by 11148@LAPTOP-HB33B0MF

------------------------------------------------------------------------------------------------------------------------

[2017-02-18 20:00:53 #1 explorer] 
[ObjectDB 2.6.9_09] javax.persistence.PersistenceException
Attempt to open a database file 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' that is currently in use by another process (error 141)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Attempt to open a database file 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' that is currently in use by another process
	at com.objectdb.o.MSG.d(MSG.java:62)
	at com.objectdb.o.LFL.G(LFL.java:939)
	at com.objectdb.o.LFL.B(LFL.java:885)
	at com.objectdb.o.LFL.B(LFL.java:794)
	at com.objectdb.o.SFL.<init>(SFL.java:235)
	at com.objectdb.o.MST.<init>(MST.java:123)
	at com.objectdb.o.MST.aN(MST.java:105)
	at com.objectdb.o.MSF.Vn(MSF.java:188)
	at com.objectdb.o.OMF.an(OMF.java:782)
	at com.objectdb.jpa.EMF.an(EMF.java:131)
	at com.objectdb.o.OMF.am(OMF.java:693)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:150)
	... 17 more

------------------------------------------------------------------------------------------------------------------------

[2017-02-18 20:01:38 #1 store] 
Database 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' is opened by 10872@LAPTOP-HB33B0MF

[2017-02-18 20:03:35 #2 store] 
Database 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' is closed by 10872@LAPTOP-HB33B0MF

------------------------------------------------------------------------------------------------------------------------

[2017-02-18 20:04:21 #1 explorer] 
[ObjectDB 2.6.9_09] javax.persistence.PersistenceException
Attempt to open a database file 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' that is currently in use by another process (error 141)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Attempt to open a database file 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' that is currently in use by another process
	at com.objectdb.o.MSG.d(MSG.java:62)
	at com.objectdb.o.LFL.G(LFL.java:939)
	at com.objectdb.o.LFL.B(LFL.java:885)
	at com.objectdb.o.LFL.B(LFL.java:794)
	at com.objectdb.o.SFL.<init>(SFL.java:235)
	at com.objectdb.o.MST.<init>(MST.java:123)
	at com.objectdb.o.MST.aN(MST.java:105)
	at com.objectdb.o.MSF.Vn(MSF.java:188)
	at com.objectdb.o.OMF.an(OMF.java:782)
	at com.objectdb.jpa.EMF.an(EMF.java:131)
	at com.objectdb.o.OMF.am(OMF.java:693)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:150)
	... 17 more

------------------------------------------------------------------------------------------------------------------------

[2017-02-18 20:04:28 #1 explorer] 
[ObjectDB 2.6.9_09] javax.persistence.PersistenceException
Attempt to open a database file 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' that is currently in use by another process (error 141)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Attempt to open a database file 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' that is currently in use by another process
	at com.objectdb.o.MSG.d(MSG.java:62)
	at com.objectdb.o.LFL.G(LFL.java:939)
	at com.objectdb.o.LFL.B(LFL.java:885)
	at com.objectdb.o.LFL.B(LFL.java:794)
	at com.objectdb.o.SFL.<init>(SFL.java:235)
	at com.objectdb.o.MST.<init>(MST.java:123)
	at com.objectdb.o.MST.aN(MST.java:105)
	at com.objectdb.o.MSF.Vn(MSF.java:188)
	at com.objectdb.o.OMF.an(OMF.java:782)
	at com.objectdb.jpa.EMF.an(EMF.java:131)
	at com.objectdb.o.OMF.am(OMF.java:693)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:150)
	... 17 more

------------------------------------------------------------------------------------------------------------------------

[2017-02-18 20:04:33 #1 store] 
Database 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' is opened by 11172@LAPTOP-HB33B0MF

[2017-02-18 20:04:43 #2 store] 
Database 'C:\Users\Kurama\Desktop\SI\1Marroia\ruralHousessDB.odb' is closed by 11172@LAPTOP-HB33B0MF

